// <auto-generated />
using System;
using GestionConveniosUCNE.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace RegistroConveniosUCNE.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20251025033704_RutaArchivo")]
    partial class RutaArchivo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("GestionConveniosUCNE.Models.Actividad", b =>
                {
                    b.Property<int>("IdActividad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenciaArchivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaActividad")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdConvenio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TituloActividad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("IdActividad");

                    b.HasIndex("CreadoPor");

                    b.HasIndex("IdConvenio");

                    b.ToTable("Actividades");
                });

            modelBuilder.Entity("GestionConveniosUCNE.Models.Alerta", b =>
                {
                    b.Property<int>("IdAlerta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Destinatarios")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DiasAnticipacion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EstadoAlerta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaEnvio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaGenerada")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdConvenio")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdAlerta");

                    b.HasIndex("IdConvenio");

                    b.ToTable("Alertas");
                });

            modelBuilder.Entity("GestionConveniosUCNE.Models.Convenio", b =>
                {
                    b.Property<int>("IdConvenio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArchivoPrincipal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Categoria")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescripcionObjetivos")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DuracionMeses")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaFirma")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoConvenio")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UltimaModificacion")
                        .HasColumnType("TEXT");

                    b.HasKey("IdConvenio");

                    b.HasIndex("CreadoPor");

                    b.ToTable("Convenios");
                });

            modelBuilder.Entity("GestionConveniosUCNE.Models.ConvenioInstitucion", b =>
                {
                    b.Property<int>("ConvenioInstitucionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdConvenio")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdInstitucion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rol")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("ConvenioInstitucionId");

                    b.HasIndex("IdConvenio");

                    b.HasIndex("IdInstitucion");

                    b.ToTable("ConvenioInstituciones");
                });

            modelBuilder.Entity("GestionConveniosUCNE.Models.ConvenioResponsable", b =>
                {
                    b.Property<int>("ConvenioResponsableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdConvenio")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdResponsable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rol")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("ConvenioResponsableId");

                    b.HasIndex("IdConvenio");

                    b.HasIndex("IdResponsable");

                    b.ToTable("ConvenioResponsables");
                });

            modelBuilder.Entity("GestionConveniosUCNE.Models.Institucion", b =>
                {
                    b.Property<int>("IdInstitucion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoInstitucion")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("IdInstitucion");

                    b.ToTable("Instituciones");
                });

            modelBuilder.Entity("GestionConveniosUCNE.Models.Responsable", b =>
                {
                    b.Property<int>("IdResponsable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cargo")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Departamento")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("IdResponsable");

                    b.ToTable("Responsables");
                });

            modelBuilder.Entity("GestionConveniosUCNE.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("IdRol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("GestionConveniosUCNE.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailInstitucional")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("IdRol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioLogin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdRol");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("GestionConveniosUCNE.Models.Actividad", b =>
                {
                    b.HasOne("GestionConveniosUCNE.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("CreadoPor");

                    b.HasOne("GestionConveniosUCNE.Models.Convenio", "Convenio")
                        .WithMany("Actividades")
                        .HasForeignKey("IdConvenio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Convenio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GestionConveniosUCNE.Models.Alerta", b =>
                {
                    b.HasOne("GestionConveniosUCNE.Models.Convenio", "Convenio")
                        .WithMany("Alertas")
                        .HasForeignKey("IdConvenio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Convenio");
                });

            modelBuilder.Entity("GestionConveniosUCNE.Models.Convenio", b =>
                {
                    b.HasOne("GestionConveniosUCNE.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("CreadoPor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GestionConveniosUCNE.Models.ConvenioInstitucion", b =>
                {
                    b.HasOne("GestionConveniosUCNE.Models.Convenio", "Convenio")
                        .WithMany("ConvenioInstituciones")
                        .HasForeignKey("IdConvenio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionConveniosUCNE.Models.Institucion", "Institucion")
                        .WithMany("ConvenioInstituciones")
                        .HasForeignKey("IdInstitucion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Convenio");

                    b.Navigation("Institucion");
                });

            modelBuilder.Entity("GestionConveniosUCNE.Models.ConvenioResponsable", b =>
                {
                    b.HasOne("GestionConveniosUCNE.Models.Convenio", "Convenio")
                        .WithMany("ConvenioResponsables")
                        .HasForeignKey("IdConvenio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionConveniosUCNE.Models.Responsable", "Responsable")
                        .WithMany("ConvenioResponsables")
                        .HasForeignKey("IdResponsable")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Convenio");

                    b.Navigation("Responsable");
                });

            modelBuilder.Entity("GestionConveniosUCNE.Models.Usuario", b =>
                {
                    b.HasOne("GestionConveniosUCNE.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("GestionConveniosUCNE.Models.Convenio", b =>
                {
                    b.Navigation("Actividades");

                    b.Navigation("Alertas");

                    b.Navigation("ConvenioInstituciones");

                    b.Navigation("ConvenioResponsables");
                });

            modelBuilder.Entity("GestionConveniosUCNE.Models.Institucion", b =>
                {
                    b.Navigation("ConvenioInstituciones");
                });

            modelBuilder.Entity("GestionConveniosUCNE.Models.Responsable", b =>
                {
                    b.Navigation("ConvenioResponsables");
                });

            modelBuilder.Entity("GestionConveniosUCNE.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
